---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: forge-provisioner-shell
  namespace: forge-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: forge-provisioner-shell
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: forge-provisioner-shell
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: forge-provisioner-shell
subjects:
- kind: ServiceAccount
  name: forge-provisioner-shell
  namespace: forge-core
