---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - forge.build
  resources:
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - forge.build
  resources:
  - builds/finalizers
  verbs:
  - update
- apiGroups:
  - forge.build
  resources:
  - builds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.forge.build
  - provisioner.forge.build
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
