apiVersion: image.forge.build/v1alpha1
kind: Build
metadata:
  labels:
    app.kubernetes.io/name: build
    app.kubernetes.io/instance: build-sample
    app.kubernetes.io/part-of: forge
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: forge
  name: build-sample
spec:
  infrastructureRef:
    apiVersion: infrastructure.forge.build/v1alpha1
    kind: Infrastructure
    name: infrastructure-sample
