name: Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "release-*"]

permissions: write-all

jobs:
  go_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Verify
        run: "make verify"

      - name: Run tests
        run: "make test"

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: forge-build/forge
